// lib/tone.ts
// اعمال لحن روی متن با دیکشنری جایگزین کلمات (نسخه بزرگ)

export type Tone = "formal" | "casual" | "literary" | "scientific" | "funny";

// ========== دیکشنری بزرگ لحن ==========
const TONE_DICTIONARIES: Record<Tone, Record<string, string>> = {
  formal: {
    // ===== فارسی =====
    "سلام": "با سلام",
    "درود": "با سلام و احترام",
    "خوبی": "حال شما چطور است",
    "چطوری": "حال شما چگونه است",
    "چه خبر": "چه خبر است",
    "ممنون": "سپاسگزارم",
    "مرسی": "متشکرم",
    "دستت درد نکنه": "از لطف شما سپاسگزارم",
    "بای": "با احترام، خدانگهدار",
    "خداحافظ": "با احترام، خدانگهدار",
    "ببخشید": "پوزش می‌طلبم",
    "معذرت می‌خوام": "پوزش می‌طلبم",
    "آره": "بله",
    "بله": "بله",
    "نه": "خیر",
    "خب": "بسیار خوب",
    "باشه": "بسیار خوب",
    "اوکی": "بسیار خوب",
    "کجایی": "کجا تشریف دارید",
    "چیکار می‌کنی": "چه کاری انجام می‌دهید",
    "می‌خوام": "قصد دارم",
    "می‌خوای": "آیا تمایل دارید",
    "فکر می‌کنم": "بر این باورم",
    "نمی‌دونم": "اطلاعی ندارم",
    "می‌دونم": "آگاه هستم",
    "دوستت دارم": "شما را دوست می‌دارم",
    "دوست دارم": "علاقه‌مند هستم",
    "قشنگ": "زیبا",
    "خوشگل": "زیبا",
    "باحال": "جالب",
    "بامزه": "خنده‌دار",
    "خسته": "خسته",
    "گشنمه": "گرسنه هستم",
    "تشنه‌ام": "تشنه هستم",
    "خوابم میاد": "خواب‌آلود هستم",
    "بیا": "تشریف بیاورید",
    "برو": "تشریف ببرید",
    "بگیر": "دریافت کنید",
    "بده": "تقدیم کنید",
    "بگو": "بفرمایید",
    "بشنو": "گوش کنید",
    "ببین": "مشاهده کنید",
    "الان": "در حال حاضر",
    "بعداً": "در آینده",
    "زود": "به‌سرعت",
    "دیر": "با تأخیر",
    "خیلی": "بسیار",
    "کم": "اندک",
    "زیاد": "فراوان",
    "همیشه": "همواره",
    "هرگز": "هرگز",
    "شاید": "احتمالاً",
    "حتماً": "قطعاً",
    "واقعاً": "به‌راستی",
    "بگو چی شد": "بفرمایید چه اتفاقی افتاد",
    "چی": "چه",
    "کی": "چه کسی",
    "کجا": "در کجا",
    "چرا": "به چه دلیل",
    "چطور": "به چه صورت",
    "چقدر": "به چه میزان",
    // ===== انگلیسی =====
    "hi": "Good day",
    "hello": "Greetings",
    "hey": "Good day",
    "yo": "Greetings",
    "sup": "How do you do",
    "what's up": "How do you do",
    "thanks": "Thank you kindly",
    "thank you": "I appreciate it",
    "thanks a lot": "I extend my sincere gratitude",
    "cheers": "With gratitude",
    "bye": "Farewell",
    "goodbye": "Farewell",
    "see ya": "Until we meet again",
    "yeah": "Indeed",
    "yep": "Certainly",
    "yup": "Indeed",
    "nope": "Certainly not",
    "nah": "Negative",
    "ok": "Very well",
    "okay": "Very well",
    "cool": "Excellent",
    "awesome": "Splendid",
    "great": "Excellent",
    "nice": "Pleasant",
    "good": "Satisfactory",
    "bad": "Unsatisfactory",
    "big": "Substantial",
    "small": "Diminutive",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "have to",
    "kinda": "somewhat",
    "sorta": "somewhat",
    "dunno": "do not know",
    "gimme": "give me",
    "lemme": "let me",
    "ya": "you",
    "u": "you",
    "r": "are",
    "pls": "please",
    "plz": "please",
    "thx": "thank you",
    "tnx": "thank you",
    "asap": "at your earliest convenience",
    "btw": "by the way",
    "fyi": "for your information",
    "idk": "I do not know",
    "imo": "in my opinion",
    "tbh": "to be honest",
    "lol": "that is amusing",
    "omg": "oh my goodness",
    "wtf": "what on earth",
    "wanna go": "would you like to go",
    "what": "pardon",
    "why": "for what reason",
    "how": "in what manner",
    "when": "at what time",
    "where": "in what location",
    "who": "which individual",
    "stop": "cease",
    "go": "proceed",
    "come": "approach",
    "look": "observe",
    "listen": "attend",
    "eat": "dine",
    "drink": "consume",
    "sleep": "rest",
    "help": "assist",
    "make": "create",
    "get": "obtain",
    "give": "provide",
    "take": "receive",
    "keep": "retain",
    "put": "place",
    "find": "locate",
    "lose": "misplace",
    "buy": "purchase",
    "sell": "vend",
    "start": "commence",
    "end": "conclude",
    "begin": "commence",
    "finish": "complete",
    "ask": "inquire",
    "tell": "inform",
    "say": "state",
    "speak": "converse",
    "think": "believe",
    "know": "be aware",
    "understand": "comprehend",
    "remember": "recall",
    "forget": "fail to recall",
    "want": "desire",
    "need": "require",
    "like": "be fond of",
    "love": "hold dear",
    "hate": "detest",
    "feel": "sense",
    "see": "observe",
    "hear": "perceive",
    "watch": "observe",
    "read": "peruse",
    "write": "compose",
    "walk": "proceed on foot",
    "run": "sprint",
    "drive": "operate a vehicle",
    "fly": "travel by air",
    "smile": "express joy",
    "laugh": "express mirth",
    "cry": "shed tears",
    "happy": "content",
    "sad": "melancholy",
    "angry": "irate",
    "tired": "weary",
    "hungry": "famished",
    "thirsty": "parched",
    "sick": "unwell",
    "healthy": "in good health",
    "pretty": "beautiful",
    "ugly": "unattractive",
    "smart": "intelligent",
    "dumb": "unintelligent",
    "fast": "rapid",
    "slow": "sluggish",
    "easy": "simple",
    "hard": "difficult",
    "hot": "warm",
    "cold": "chilly",
    "new": "recent",
    "old": "aged",
    "young": "youthful",
    "rich": "wealthy",
    "poor": "impoverished",
    "friend": "companion",
    "buddy": "companion",
    "dude": "sir",
    "guy": "gentleman",
    "kid": "child",
    "baby": "infant",
    "mom": "mother",
    "dad": "father",
    "wife": "spouse",
    "husband": "spouse",
    "job": "occupation",
    "money": "funds",
    "home": "residence",
    "car": "automobile",
    "food": "nourishment",
    "water": "beverage",
    "today": "on this day",
    "tomorrow": "on the morrow",
    "yesterday": "on the previous day",
    "now": "at present",
    "later": "subsequently",
    "soon": "shortly",
    "always": "invariably",
    "never": "at no time",
    "maybe": "perhaps",
    "sure": "certainly",
    "really": "genuinely",
    "very": "exceedingly",
    "too": "excessively",
    "much": "a great deal",
    "many": "numerous",
    "few": "a small number of",
  },
  casual: {
    // ===== فارسی =====
    "با سلام": "سلام",
    "با سلام و احترام": "درود",
    "سپاسگزارم": "مرسی",
    "متشکرم": "ممنون",
    "از لطف شما سپاسگزارم": "دستت درد نکنه",
    "با احترام": "بای",
    "پوزش می‌طلبم": "ببخشید",
    "بله": "آره",
    "خیر": "نه",
    "بسیار خوب": "خب",
    "حال شما چطور است": "خوبی؟",
    "حال شما چگونه است": "چطوری؟",
    "کجا تشریف دارید": "کجایی؟",
    "قصد دارم": "می‌خوام",
    "بر این باورم": "فکر می‌کنم",
    "اطلاعی ندارم": "نمی‌دونم",
    "آگاه هستم": "می‌دونم",
    "شما را دوست می‌دارم": "دوستت دارم",
    "علاقه‌مند هستم": "دوست دارم",
    "زیبا": "قشنگ",
    "تشریف بیاورید": "بیا",
    "تشریف ببرید": "برو",
    "دریافت کنید": "بگیر",
    "تقدیم کنید": "بده",
    "بفرمایید": "بگو",
    "گوش کنید": "بشنو",
    "مشاهده کنید": "ببین",
    "در حال حاضر": "الان",
    "در آینده": "بعداً",
    "به‌سرعت": "زود",
    "با تأخیر": "دیر",
    "بسیار": "خیلی",
    "اندک": "کم",
    "فراوان": "زیاد",
    "همواره": "همیشه",
    "احتمالاً": "شاید",
    "قطعاً": "حتماً",
    "به‌راستی": "واقعاً",
    "چه": "چی",
    "چه کسی": "کی",
    "در کجا": "کجا",
    "به چه دلیل": "چرا",
    "به چه صورت": "چطور",
    "به چه میزان": "چقدر",
    // ===== انگلیسی =====
    "good day": "hey",
    "greetings": "hey",
    "how do you do": "what's up",
    "thank you kindly": "thanks",
    "i appreciate it": "thanks",
    "i extend my sincere gratitude": "thanks a ton",
    "with gratitude": "cheers",
    "farewell": "bye",
    "until we meet again": "see ya",
    "indeed": "yeah",
    "certainly": "yep",
    "certainly not": "nope",
    "negative": "nah",
    "very well": "ok",
    "excellent": "cool",
    "splendid": "awesome",
    "pleasant": "nice",
    "satisfactory": "good",
    "unsatisfactory": "bad",
    "substantial": "big",
    "diminutive": "small",
    "going to": "gonna",
    "want to": "wanna",
    "have to": "gotta",
    "somewhat": "kinda",
    "do not know": "dunno",
    "give me": "gimme",
    "let me": "lemme",
    "you": "ya",
    "are": "r",
    "please": "pls",
    "thank you": "thx",
    "at your earliest convenience": "asap",
    "by the way": "btw",
    "for your information": "fyi",
    "i do not know": "idk",
    "in my opinion": "imo",
    "to be honest": "tbh",
    "that is amusing": "lol",
    "oh my goodness": "omg",
    "what on earth": "wtf",
    "pardon": "what",
    "for what reason": "why",
    "in what manner": "how",
    "at what time": "when",
    "in what location": "where",
    "which individual": "who",
    "cease": "stop",
    "proceed": "go",
    "approach": "come",
    "observe": "look",
    "attend": "listen",
    "dine": "eat",
    "consume": "drink",
    "rest": "sleep",
    "assist": "help",
    "create": "make",
    "obtain": "get",
    "provide": "give",
    "receive": "take",
    "retain": "keep",
    "place": "put",
    "locate": "find",
    "misplace": "lose",
    "purchase": "buy",
    "vend": "sell",
    "commence": "start",
    "conclude": "end",
    "complete": "finish",
    "inquire": "ask",
    "inform": "tell",
    "state": "say",
    "converse": "speak",
    "believe": "think",
    "be aware": "know",
    "comprehend": "understand",
    "recall": "remember",
    "fail to recall": "forget",
    "desire": "want",
    "require": "need",
    "be fond of": "like",
    "hold dear": "love",
    "detest": "hate",
    "sense": "feel",
    "perceive": "hear",
    "peruse": "read",
    "compose": "write",
    "sprint": "run",
    "content": "happy",
    "melancholy": "sad",
    "irate": "angry",
    "weary": "tired",
    "famished": "hungry",
    "parched": "thirsty",
    "unwell": "sick",
    "in good health": "healthy",
    "beautiful": "pretty",
    "unattractive": "ugly",
    "intelligent": "smart",
    "rapid": "fast",
    "sluggish": "slow",
    "simple": "easy",
    "difficult": "hard",
    "warm": "hot",
    "chilly": "cold",
    "recent": "new",
    "aged": "old",
    "youthful": "young",
    "wealthy": "rich",
    "impoverished": "poor",
    "companion": "buddy",
    "sir": "dude",
    "gentleman": "guy",
    "child": "kid",
    "infant": "baby",
    "mother": "mom",
    "father": "dad",
    "spouse": "partner",
    "occupation": "job",
    "funds": "money",
    "residence": "home",
    "automobile": "car",
    "nourishment": "food",
    "beverage": "drink",
    "on this day": "today",
    "on the morrow": "tomorrow",
    "on the previous day": "yesterday",
    "at present": "now",
    "subsequently": "later",
    "shortly": "soon",
    "invariably": "always",
    "at no time": "never",
    "perhaps": "maybe",
    "genuinely": "really",
    "exceedingly": "very",
    "excessively": "too",
    "a great deal": "much",
    "numerous": "many",
    "a small number of": "few",
  },
  literary: {
    // ===== فارسی =====
    "سلام": "درود",
    "خوبی": "احوالت چطور است",
    "ممنون": "سپاس بی‌کران",
    "مرسی": "سپاس",
    "بای": "بدرود",
    "خداحافظ": "بدرود",
    "دوستت دارم": "دل در گروت دارم",
    "دوست دارم": "دل‌بسته‌ام",
    "زیبا": "دل‌انگیز",
    "قشنگ": "دل‌فریب",
    "خوشحال": "شادمان",
    "غمگین": "دل‌افسرده",
    "ناراحت": "دل‌تنگ",
    "بزرگ": "عظیم",
    "کوچک": "خرد",
    "سریع": "چابک",
    "باهوش": "تیزهوش",
    "خسته": "فرسوده",
    "دوست": "یار",
    "رفیق": "همدم",
    "عشق": "دلبستگی",
    "قلب": "دل",
    "چشم": "دیده",
    "شب": "شبانگاه",
    "روز": "روزگار",
    "صبح": "بامداد",
    "عصر": "پسین",
    "ماه": "مهتاب",
    "خورشید": "مهر",
    "ستاره": "اختر",
    "آسمان": "سپهر",
    "زمین": "خاک",
    "دریا": "یم",
    "کوه": "کوهسار",
    "گل": "گلرخ",
    "پرنده": "مرغ",
    "خانه": "سرا",
    "زندگی": "زندگانی",
    "مرگ": "فنا",
    "زمان": "روزگار",
    "همیشه": "هماره",
    "هرگز": "هرگز مباد",
    // ===== انگلیسی =====
    "hi": "Hail",
    "hello": "Hail",
    "hey": "Hail",
    "thanks": "My deepest gratitude",
    "thank you": "My sincere thanks",
    "bye": "Farewell",
    "goodbye": "Farewell",
    "i love you": "My heart yearns for thee",
    "love": "affection",
    "beautiful": "beauteous",
    "pretty": "fair",
    "happy": "joyous",
    "sad": "melancholic",
    "angry": "wrathful",
    "tired": "weary",
    "friend": "companion",
    "buddy": "comrade",
    "heart": "bosom",
    "eyes": "orbs",
    "night": "eventide",
    "day": "morn to eve",
    "morning": "morn",
    "evening": "eventide",
    "moon": "lunar orb",
    "sun": "solar sphere",
    "star": "celestial light",
    "sky": "firmament",
    "earth": "terra",
    "sea": "briny deep",
    "mountain": "mountain peak",
    "flower": "blossom",
    "bird": "winged creature",
    "home": "abode",
    "life": "existence",
    "death": "mortality",
    "time": "tempus",
    "always": "evermore",
    "never": "ne'er",
    "yes": "aye",
    "no": "nay",
    "maybe": "perchance",
    "very": "exceeding",
    "big": "vast",
    "small": "tiny",
    "fast": "swift",
    "slow": "leaden",
    "smart": "sagacious",
    "soul": "spirit",
    "dream": "vision",
    "hope": "aspiration",
    "fear": "trepidation",
    "joy": "elation",
    "sorrow": "melancholy",
    "truth": "verity",
    "beauty": "splendor",
    "wisdom": "sagacity",
    "courage": "valor",
    "silence": "stillness",
    "voice": "voice divine",
  },
  scientific: {
    // ===== فارسی =====
    "خوب": "مطلوب",
    "بد": "نامطلوب",
    "زیاد": "قابل توجه",
    "کم": "ناچیز",
    "ممنون": "قدردانی می‌کنم",
    "می‌خوام": "قصد دارم",
    "فکر می‌کنم": "بر این باورم",
    "نمی‌دونم": "اطلاعات کافی ندارم",
    "می‌دونم": "آگاه هستم",
    "بزرگ": "قابل توجه",
    "کوچک": "ناچیز",
    "سریع": "با سرعت بالا",
    "کند": "با سرعت پایین",
    "آسان": "ساده",
    "سخت": "پیچیده",
    "گرم": "با دمای بالا",
    "سرد": "با دمای پایین",
    "جدید": "نوین",
    "قدیمی": "کهن",
    "مهم": "حائز اهمیت",
    "بی‌اهمیت": "فاقد اهمیت",
    "درست": "صحیح",
    "غلط": "ناصحیح",
    "مشکل": "چالش",
    "راه‌حل": "راهکار",
    "روش": "متدولوژی",
    "نتیجه": "نتیجه‌گیری",
    "تحقیق": "پژوهش",
    "دانش": "معرفت",
    "علم": "دانش",
    "مطالعه": "بررسی",
    "تحلیل": "واکاوی",
    "بررسی": "ارزیابی",
    "تست": "آزمون",
    "آزمایش": "تست",
    "مثال": "نمونه",
    "داده": "داده",
    "اطلاعات": "داده‌ها",
    "نمودار": "نمودار",
    "درصد": "درصد",
    "میانگین": "میانگین",
    // ===== انگلیسی =====
    "good": "optimal",
    "bad": "suboptimal",
    "a lot": "significant",
    "much": "considerable",
    "little": "negligible",
    "big": "substantial",
    "small": "minimal",
    "fast": "rapid",
    "slow": "gradual",
    "easy": "straightforward",
    "hard": "complex",
    "hot": "high-temperature",
    "cold": "low-temperature",
    "new": "novel",
    "old": "archaic",
    "important": "significant",
    "unimportant": "insignificant",
    "right": "correct",
    "wrong": "incorrect",
    "problem": "challenge",
    "solution": "resolution",
    "method": "methodology",
    "result": "outcome",
    "research": "investigation",
    "knowledge": "understanding",
    "science": "empirical study",
    "study": "examination",
    "analyze": "examine",
    "check": "evaluate",
    "test": "assessment",
    "example": "illustration",
    "data": "dataset",
    "information": "data",
    "think": "hypothesize",
    "believe": "postulate",
    "know": "be cognizant of",
    "maybe": "potentially",
    "shows": "demonstrates",
    "use": "utilize",
    "help": "facilitate",
    "make": "produce",
    "get": "obtain",
    "find": "identify",
    "start": "initiate",
    "end": "conclude",
    "increase": "augment",
    "decrease": "diminish",
    "improve": "enhance",
    "change": "modify",
    "explain": "elucidate",
    "understand": "comprehend",
    "measure": "quantify",
    "compare": "contrast",
    "estimate": "approximate",
    "calculate": "compute",
    "very": "significantly",
    "really": "demonstrably",
    "clearly": "evidently",
    "obviously": "demonstrably",
    "probably": "likely",
    "possibly": "potentially",
  },
  funny: {
    // ===== فارسی =====
    "سلام": "سلام سلام! 👋",
    "خوبی": "چطوری رفیق؟ 😄",
    "چطوری": "چه خبر رفیق؟ 😎",
    "ممنون": "دستت درد نکنه! 🙌",
    "مرسی": "مرسی داداش! 🤙",
    "بای": "یالا برو دیگه! 😄",
    "خداحافظ": "بای بای! 🐊",
    "ببخشید": "ببخشید دیگه! 😅",
    "آره": "آره بابا! ✌️",
    "نه": "نه دیگه! 🙅",
    "خب": "خب دیگه! 🤷",
    "باشه": "باشه بابا! 😏",
    "اوکی": "اوکی پویکی! 👌",
    "دوستت دارم": "عاشقتم داداش! ❤️",
    "قشنگ": "خیلی خوشگله! 😍",
    "خوشحال": "ذوق مرگ شدم! 🤩",
    "غمگین": "اعصابم خورده! 😢",
    "خسته": "داغونم! 😴",
    "گشنمه": "دارم از گشنگی می‌میرم! 🍕",
    "خوابم میاد": "چشمام داره بسته می‌شه! 😴",
    "بزرگ": "خیلی گنده! 🐘",
    "کوچک": "قد یه نخود! 🫛",
    "سریع": "برق آسا! ⚡",
    "کند": "مثل لاک‌پشت! 🐢",
    "باهوش": "خیلی زرنگ! 🧠",
    "دوست": "رفیق جون! 🤝",
    "باحال": "خیلی باحال! 😎",
    // ===== انگلیسی =====
    "hi": "Yo! 👋",
    "hello": "Well hello there! 😄",
    "hey": "Hey you! 👋",
    "thanks": "Thanks a bunch! 🙌",
    "thank you": "You're a lifesaver! 🙏",
    "bye": "Catch ya later! 🐊",
    "goodbye": "Peace out! ✌️",
    "yes": "Yasss! 🎉",
    "yeah": "Hell yeah! 🤘",
    "no": "Nope, nada! 🙅",
    "nope": "Nah, no way! 🙅‍♂️",
    "ok": "Okie dokie! 👌",
    "okay": "Okie dokie! 👌",
    "cool": "Totally rad! 😎",
    "awesome": "Freakin' awesome! 🤩",
    "great": "Super duper! 🌟",
    "nice": "Sweet! 🍬",
    "good": "Pretty darn good! 👍",
    "bad": "Kinda sucky! 😬",
    "big": "Huge-mongous! 🐘",
    "small": "Tiny widdle! 🐜",
    "fast": "Zoom zoom! 💨",
    "slow": "Slowpoke! 🐌",
    "smart": "Brainiac! 🧠",
    "friend": "Buddy ol' pal! 🤝",
    "buddy": "Amigo! 🤜🤛",
    "dude": "Bro! 😎",
    "i love you": "I freakin' love you! ❤️",
    "love": "Lurve! 💕",
    "happy": "Over the moon! 🌙",
    "sad": "Bummed out! 😢",
    "tired": "Dead tired! 😴",
    "hungry": "Hangry! 🍕",
    "what": "Whaaat? 🤔",
    "why": "Whyyyyy? 😩",
    "how": "How in the world? 🤯",
    "wow": "Holy cow! 🐄",
    "omg": "OMGosh! 😱",
    "lol": "LOLz! 😂",
    "please": "Pretty please! 🥺",
    "sorry": "Sooo sorry! 😅",
    "wait": "Hold your horses! 🐴",
    "stop": "Chill out! ✋",
    "go": "Vamoose! 🏃",
    "come": "Come hither! 🚶",
    "look": "Take a gander! 👀",
    "listen": "Lend me your ear! 👂",
    "eat": "Chow down! 🍔",
    "drink": "Chug it! 🍺",
    "sleep": "Hit the hay! 🛏️",
    "help": "Gimme a hand! 🖐️",
    "money": "Cold hard cash! 💰",
    "food": "Grub! 🍔",
    "car": "Ride! 🚗",
    "home": "Crib! 🏠",
    "job": "Hustle! 💼",
  },
};

// اعمال لحن روی متن
export function applyTone(text: string, tone: Tone): string {
  const dictionary = TONE_DICTIONARIES[tone];
  if (!dictionary) return text;

  let result = text;

  // مرتب‌سازی بر اساس طول (بلندترها اول)
  const sortedEntries = Object.entries(dictionary).sort(
    (a, b) => b[0].length - a[0].length
  );

  // جایگزینی کلمات
  sortedEntries.forEach(([from, to]) => {
    // برای فارسی از \b استفاده نمی‌کنیم چون با یونیکد مشکل داره
    const isPersian = /[\u0600-\u06FF]/.test(from);

    if (isPersian) {
      // برای فارسی: جایگزینی ساده
      const regex = new RegExp(escapeRegex(from), "g");
      result = result.replace(regex, to);
    } else {
      // برای انگلیسی: با word boundary
      const regex = new RegExp(`\\b${escapeRegex(from)}\\b`, "gi");
      result = result.replace(regex, (match) => {
        // حفظ case
        if (
          match[0] === match[0].toUpperCase() &&
          match[0] !== match[0].toLowerCase()
        ) {
          return to.charAt(0).toUpperCase() + to.slice(1);
        }
        return to;
      });
    }
  });

  return result;
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function getToneLabel(tone: Tone): string {
  const labels: Record<Tone, string> = {
    formal: "🎩 رسمی",
    casual: "😎 خودمانی",
    literary: "📚 ادبی",
    scientific: "🧪 علمی",
    funny: "🎭 طنز",
  };
  return labels[tone] || tone;
}